bug:
  - "(bug|Bug)"
documentation:
  - "(documentation|Documentation)"
firebase:
  - "(firebase|Firebase|firestore|Firestore|emulator|Emulator|storage|Storage)"
UI/UX:
  - "(UI|ui|UX|ux|screen|width|icon|height|button|page|css|CSS|margin|padding)"
help wanted:
  - "help"
good first issue:
  - "good first issue"
CI/CD:
  - "CI/CD"
dependency:
  - "(dependency|dependencies|npm)"
Urgent:
  - "(Urgent|urgent|important)"
borken:
  - "(broken|Broken|not working)"
feature:
  - (Feature|feature|add|Add|ADD)
