export const CLEAR_AUTH_PROFILE_STATE = "CLEAR_AUTH_PROFILE_STATE";
export const CLEAR_AUTH_VERIFY_EMAIL_STATE = "CLEAR_AUTH_VERIFY_EMAIL_STATE";
export const CLEAR_AUTH_RECOVER_PASSWORD_STATE =
  "CLEAR_AUTH_RECOVER_PASSWORD_STATE";
export const CLEAR_PROFILE_EDIT_STATE = "CLEAR_PROFILE_EDIT_STATE";
export const CLEAR_ORG_GENERAL_STATE = "CLEAR_ORG_GENERAL_STATE";
export const CLEAR_PROFILE_DATA_STATE = "CLEAR_PROFILE_DATA_STATE";
export const CLEAR_ORG_USER_STATE = "CLEAR_ORG_USER_STATE";
export const CLEAR_USER_PROFILE_DATA_STATE = "CLEAR_USER_PROFILE_DATA_STATE";
export const CLEAR_ORG_DATA_STATE = "CLEAR_ORG_DATA_STATE";
export const CLEAR_EDITOR_STATE = "CLEAR_EDITOR_STATE";
export const CLEAR_TUTORIALS_BASIC_STATE = "CLEAR_TUTORIALS_BASIC_STATE";
export const CLEAR_CREATE_TUTORIALS_STATE = "CLEAR_CREATE_TUTORIALS_STATE";
export const CLEAR_CURRENT_TUTORIAL_STATE = "CLEAR_CURRENT_TUTORIAL_STATE";
export const CLEAR_TUTORIAL_IMAGES_STATE = "CLEAR_TUTORIAL_IMAGES_STATE";
export const CLEAR_POST_DATA_STATE = "CLEAR_POST_DETAILS_STATE";

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const SET_VERIFY_EMAIL_FAIL = "SET_VERIFY_EMAIL_FAIL";

export const EMAIL_VERIFY_START = "EMAIL_VERIFY_START";
export const EMAIL_VERIFY_SUCCESS = "EMAIL_VERIFY_SUCCESS";
export const EMAIL_VERIFY_FAIL = "EMAIL_VERIFY_FAIL";

export const SEND_RESET_EMAIL_START = "SEND_RESET_EMAIL_START";
export const SEND_RESET_EMAIL_SUCCESS = "SEND_RESET_EMAIL_SUCCESS";
export const SEND_RESET_EMAIL_FAIL = "SEND_RESET_EMAIL_FAIL";

export const PASSWORD_RECOVERY_START = "PASSWORD_RECOVERY_START";
export const PASSWORD_RECOVERY_SUCCESS = "PASSWORD_RECOVERY_SUCCESS";
export const PASSWORD_RECOVERY_FAIL = "PASSWORD_RECOVERY_FAIL";

export const VERIFY_RESET_CODE_START = "VERIFY_RESET_CODE_START";
export const VERIFY_RESET_CODE_SUCCESS = "VERIFY_RESET_CODE_SUCCESS";
export const VERIFY_RESET_CODE_FAIL = "VERIFY_RESET_CODE_FAIL";

export const RESEND_VERIFY_EMAIL_START = "RESEND_VERIFY_EMAIL_START";
export const RESEND_VERIFY_EMAIL_SUCCESS = "RESEND_VERIFY_EMAIL_SUCCESS";
export const RESEND_VERIFY_EMAIL_FAIL = "RESEND_VERIFY_EMAIL_FAIL";

export const PROFILE_EDIT_START = "PROFILE_EDIT_START";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL";

export const INITIAL_SETUP_START = "INITIAL_SETUP_START";
export const INITIAL_SETUP_SUCCESS = "INITIAL_SETUP_SUCCESS";
export const INITIAL_SETUP_FAIL = "INITIAL_SETUP_FAIL";

export const GET_PROFILE_DATA_START = "GET_PROFILE_DATA_START";
export const GET_PROFILE_DATA_SUCCESS = "GET_PROFILE_DATA_SUCCESS";
export const GET_PROFILE_DATA_FAIL = "GET_PROFILE_DATA_FAIL";
export const GET_PROFILE_DATA_END = "GET_PROFILE_DATA_END";

export const SET_CURRENT_ORG_PERMISSIONS_START =
  "SET_CURRENT_ORG_PERMISSIONS_START";
export const SET_CURRENT_ORG_PERMISSIONS_SUCCESS =
  "SET_CURRENT_ORG_PERMISSIONS_SUCCESS";
export const SET_CURRENT_ORG_PERMISSIONS_FAIL =
  "SET_CURRENT_ORG_PERMISSIONS_FAIL";

export const GET_ORG_USER_DATA_START = "GET_ORG_USER_DATA_START";
export const GET_ORG_USER_DATA_SUCCESS = "GET_ORG_USER_DATA_SUCCESS";
export const GET_ORG_USER_DATA_FAIL = "GET_ORG_USER_DATA_FAIL";

export const ADD_ORG_USER_START = "ADD_ORG_USER_START";
export const ADD_ORG_USER_SUCCESS = "ADD_ORG_USER_SUCCESS";
export const ADD_ORG_USER_FAIL = "ADD_ORG_USER_FAIL";

export const DELETE_ORG_START = "DELETE_ORG_START";
export const DELETE_ORG_SUCCESS = "DELETE_ORG_SUCCESS";
export const DELETE_ORG_FAIL = "DELETE_ORG_FAIL";

export const GET_ORG_GENERAL_START = "GET_ORG_GENERAL_START";
export const GET_ORG_GENERAL_SUCCESS = "GET_ORG_GENERAL_SUCCESS";
export const GET_ORG_GENERAL_FAIL = "GET_ORG_GENERAL_FAIL";

export const EDIT_ORG_GENERAL_START = "EDIT_ORG_GENERAL_START";
export const EDIT_ORG_GENERAL_SUCCESS = "EDIT_ORG_GENERAL_SUCCESS";
export const EDIT_ORG_GENERAL_FAIL = "EDIT_ORG_GENERAL_FAIL";
export const CLEAR_EDIT_ORG_GENERAL = "CLEAR_EDIT_ORG_GENERAL";

export const GET_USER_DATA_START = "GET_USER_DATA_START";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";

export const GET_ORG_DATA_START = "GET_ORG_DATA_START";
export const GET_ORG_DATA_SUCCESS = "GET_ORG_DATA_SUCCESS";
export const GET_ORG_DATA_FAIL = "GET_ORG_DATA_FAIL";

export const SET_EDITOR_DATA = "SET_EDITOR_DATA";

export const GET_USER_TUTORIALS_BASIC_START = "GET_USER_TUTORIALS_BASIC_START";
export const GET_USER_TUTORIALS_BASIC_SUCCESS =
  "GET_USER_TUTORIALS_BASIC_SUCCESS";
export const GET_USER_TUTORIALS_BASIC_FAIL = "GET_USER_TUTORIALS_BASIC_FAIL";

export const GET_ORG_TUTORIALS_BASIC_START = "GET_ORG_TUTORIALS_BASIC_START";
export const GET_ORG_TUTORIALS_BASIC_SUCCESS =
  "GET_ORG_TUTORIALS_BASIC_SUCCESS";
export const GET_ORG_TUTORIALS_BASIC_FAIL = "GET_ORG_TUTORIALS_BASIC_FAIL";

export const CREATE_TUTORIAL_START = "CREATE_TUTORIAL_START";
export const CREATE_TUTORIAL_SUCCESS = "CREATE_TUTORIAL_SUCCESS";
export const CREATE_TUTORIAL_FAIL = "CREATE_TUTORIAL_FAIL";

export const CREATE_TUTORIAL_STEP_START = "CREATE_TUTORIAL_STEP_START";
export const CREATE_TUTORIAL_STEP_SUCCESS = "CREATE_TUTORIAL_STEP_SUCCESS";
export const CREATE_TUTORIAL_STEP_FAIL = "CREATE_TUTORIAL_STEP_FAIL";

export const GET_CURRENT_TUTORIAL_START = "GET_CURRENT_TUTORIAL_START";
export const GET_CURRENT_TUTORIAL_SUCCESS = "GET_CURRENT_TUTORIAL_SUCCESS";
export const GET_CURRENT_TUTORIAL_FAIL = "GET_CURRENT_TUTORIAL_FAIL";

export const SET_CURRENT_STEP_NO = "SET_CURRENT_STEP_NO";

export const TUTORIAL_IMAGE_UPLOAD_START = "TUTORIAL_IMAGE_UPLOAD_START";
export const TUTORIAL_IMAGE_UPLOAD_SUCCESS = "TUTORIAL_IMAGE_UPLOAD_SUCCESS";
export const TUTORIAL_IMAGE_UPLOAD_FAIL = "TUTORIAL_IMAGE_UPLOAD_FAIL";

export const TUTORIAL_IMAGE_DELETE_START = "TUTORIAL_IMAGE_DELETE_START";
export const TUTORIAL_IMAGE_DELETE_SUCCESS = "TUTORIAL_IMAGE_DELETE_SUCCESS";
export const TUTORIAL_IMAGE_DELETE_FAIL = "TUTORIAL_IMAGE_DELETE_FAIL";

export const GET_LAUNCHED_ORGS_START = "GET_LAUNCHED_ORGS_START";
export const GET_LAUNCHED_ORGS_SUCCESS = "GET_LAUNCHED_ORGS_SUCCESS";
export const GET_LAUNCHED_ORGS_FAIL = "GET_LAUNCHED_ORGS_FAIL";

export const GET_POST_DATA_START = "GET_POST_DETAILS_START";
export const GET_POST_DATA_SUCCESS = "GET_POST_DETAILS_SUCCESS";
export const GET_POST_DATA_FAIL = "GET_POST_DETAILS_FAILED";

export const GET_COMMENT_DATA_START = "GET_COMMENT_DATA_START";
export const GET_COMMENT_DATA_SUCCESS = "GET_COMMENT_DATA_SUCCESS";
export const GET_COMMENT_DATA_FAIL = "GET_COMMENT_DATA_FAIL";

export const GET_REPLIES_START = "GET_REPLIES_START";
export const GET_REPLIES_SUCCESS = "GET_REPLIES_SUCCESS";
export const GET_REPLIES_FAIL = "GET_REPLIES_FAIL";

export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const GET_STEPS_DATA_START = "GET_STEPS_DETAILS_START";
export const GET_STEPS_DATA_SUCCESS = "GET_STEPS_DETAILS_SUCCESS";
export const GET_STEPS_DATA_FAIL = "GET_STEPS_DETAILS_FAILED";

export const GET_TUTORIAL_FEED_START = "GET_TUTORIAL_FEED_START";
export const GET_TUTORIAL_FEED_SUCCESS = "GET_TUTORIAL_FEED_SUCCESS";
export const GET_TUTORIAL_FEED_FAILED = "GET_TUTORIAL_FEED_FAILED";

export const ADD_COMMENT_LIKE_START = "ADD_COMMENT_LIKE_START";
export const ADD_COMMENT_LIKE_SUCCESS = "ADD_COMMENT_LIKE_SUCCESS";
export const ADD_COMMENT_LIKE_FAILED = "ADD_COMMENT_LIKE_FAILED";


